[package]
name = "ballot"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.9.6"
borsh = "0.9.3"
thiserror = "1.0.30"

[dev-dependencies]
solana-sdk = "1.9.6"

[lib]
crate-type = ["cdylib", "lib"]
